### ISSUE TITLE
Codebase Audit: Managing Mutations

### ISSUE THREAD

**Issue by mps114** [onaio/gisida-react#74]
https://docs.google.com/document/d/1oh15Z9K4mzN67SvV4j64fb1hnj1OQcQUMEWyj1fghCU/edit?usp=sharing

**Comment by cKellyDesign** [comment]
Components ->

App - ALL GOOD
Charts
DetailView ->
Depending on what parsedBasicInfo[i] is, possible mutation https://github.com/onaio/gisida-react/blob/master/src/lib/components/DetailView/DetailView.js#L87 
Export - ALL GOOD
Filter
FilterSelector
Lots of defining without copying: https://github.com/onaio/gisida-react/blob/master/src/lib/components/FilterSelector/FilterSelector.js#L8-L17 
Layer - ALL GOOD
Layers - ALL GOOD (but should double check with props)
Legend - https://github.com/onaio/gisida-react/blob/master/src/lib/components/Legend/Legend.js#L60 
Map
https://github.com/onaio/gisida-react/blob/master/src/lib/components/Map/Map.js#L134
https://github.com/onaio/gisida-react/blob/master/src/lib/components/Map/Map.js#L138
same as above but with parentLayer on the next loop
https://github.com/onaio/gisida-react/blob/master/src/lib/components/Map/Map.js#L168 
https://github.com/onaio/gisida-react/blob/master/src/lib/components/Map/Map.js#L248 
https://github.com/onaio/gisida-react/blob/master/src/lib/components/Map/Map.js#L386 , depends on layersObj which comes from this.props. If this.props doesn't do any mutating then should be all good
Menu -  ALL GOOD
Spinner - ALL GOOD
StyleSelector - ALL GOOD
ThemeSwitcher - ALL GOOD
TimeSeriesSlider ->
I believe it’s only passing in a string, but just in case an obj or array is being passed in https://github.com/onaio/gisida-react/blob/master/src/lib/components/TimeSeriesSlider/TimeSeriesSlider.js#L14 
same as above, https://github.com/onaio/gisida-react/blob/master/src/lib/components/TimeSeriesSlider/TimeSeriesSlider.js#L52 
done multiple more times with the code below the one noted above, not entirely sure what kind of values are being passed in but could easily see an issue arriving 
TitleBar - ALL GOOD


Question about this.setState() ->
Done differently here, https://github.com/onaio/gisida-react/blob/master/src/lib/components/FilterSelector/FilterSelector.js#L8-L17 than here, https://github.com/onaio/gisida-react/blob/master/src/lib/components/DetailView/DetailView.js#L35-L37. Could the second one possibly be mutating because because this.state is not copied? If so, this could be an issue because it is done like this often

**Comment by cKellyDesign** [comment]
https://docs.google.com/document/d/1ma2rCS2rOW6A8Y1a5xqMVvVTv2EKNz2q0bUJFrAEL6I/edit?usp=sharing
